### ISSUE TITLE
GM8Decompiler crashes

### ISSUE THREAD

**Issue by Mati3D** [OpenGM8/GM8Decompiler#22] opened 2023-01-06 22:36 UTC
GM8Decompiler crashes everytime i press a key or drag a file into it

**Comment by Adamcake** [comment] 2023-01-09 22:55
When you say it "crashes", what indicates that it has crashed? Is there an error message in the console, for example?

**Comment by Mati3D** [comment] 2023-01-10 19:10
nope it just closes no error(s) nothing at all

**Comment by Adamcake** [comment] 2023-01-11 14:15
You mean that it closes after you press a key after it says "press any key to continue"? If so, that is expected, it does that after telling you how to use the tool correctly. You use it by dragging a game onto decompiler.exe (the file, not the console window) and it'll produce a gmk if successful.

**Comment by Mati3D** [comment] 2023-01-11 17:58
it closes if i press any key anytime it doesnt matter if it says "press any key to continue" or not it will still close i have alredy tried dragging the game into the console window and the same still happens

**Comment by Adamcake** [comment] 2023-01-12 16:00
You don't need to do anything with a console window. If you drag the game onto decompiler.exe inside your file explorer, it'll try to decompile it. If it doesn't work then your game probably isn't made with GameMaker 8.

**Comment by Adamcake** [comment] 2023-01-12 16:04
Also, running it via a console (`decompiler.exe game_name_here.exe`) instead of dragging the files onto each other would let you see the program's output - it's most likely not crashing but just exiting expectedly.

**Comment by TheLogicalFounder** [comment] 2023-06-26 19:17
where does being decompiled?

**Comment by Anton2GB** [comment] 2023-09-12 15:19
The error is still not fixed. This problem is also observed in other fix shells programs for GameMaker. I think the Windows 10 update is to blame, something went wrong.

**Comment by p0008874** [comment] 2023-09-12 15:25
Uploading HPRHhIcfXu.mp4…

> The error is still not fixed. This problem is also observed in other fix shells programs for GameMaker. I think the Windows 10 update is to blame, something went wrong.

Are you sure?
I used GM8Decompiler from OpenGMK.

**Comment by p0008874** [comment] 2023-09-12 15:26
> The error is still not fixed. This problem is also observed in other fix shells programs for GameMaker. I think the Windows 10 update is to blame, something went wrong.

Are you sure?
I used GM8Decompiler from OpenGMK.

https://github.com/OpenGMK/GM8Decompiler/assets/75534590/5602d017-727d-49bd-8d84-da8079f9c88e

**Comment by Anton2GB** [comment] 2023-09-12 16:19
> > The error is still not fixed. This problem is also observed in other fix shells programs for GameMaker. I think the Windows 10 update is to blame, something went wrong.
> 
> Are you sure? I used GM8Decompiler from OpenGMK.
> 
>  HPRHhIcfXu.mp4

Thank you, friend. 
I started the decompiler, and tried to enter the path there or transfer it directly to the decompiler under the drag & drop tool - the decompiler closed itself, without a result. 
At the same time, without starting the decompiler with dragging the gm program, everything works. 
Solving the problem will be useful for those who have also encountered such a problem, and for the author of the comment thread. 
Thanks again, cured.

**Comment by Adamcake** [comment] 2023-09-12 19:09
I'm glad you were able to solve your problem, but I'm going to close this issue because I don't think there's any more meaningful discussion to be had here. In 100% of recent cases the decompiler "crashing" was due to either being used incorrectly, or being used on a game that wasn't made with GameMaker 8. When the program ends, the console closes itself. This is intended behaviour of your OS. There's also no possible way a Windows update could cause any problems; this tool is cross-platform and doesn't need to use any Windows libraries to do its job of converting between two file formats.

If anyone is finding our tools hard to use then they're welcome to join the OpenGMK discord server, we have a community of people ready and willing to help. We would appreciate Github being used for technical issues only.

**Closed as completed by Adamcake** 2023-09-12 19:09 UTC
